### ISSUE TITLE
Abillity to exclude some remotes from scope-sync

### ISSUE THREAD

**Issue by f1nnix** [f1nnix/rc#2]
```yml
  store:
    remote: data_51
    remote_path: /
    local_path: /store
    excluded: true
```

1. `rc` or `rc down` should not sync  **store** by default.
2. Passing option `--sync-excluded` should sync all remotes, including excluded.
